### ISSUE TITLE
Kernel restarter

### ISSUE THREAD

**Issue by mathicm** [harripd/H2MMpythonlib#2]
Hi, I tried to run your H2MM code but I keep getting **KernelRestarter: restarting kernel (1/5), keep random ports**, specifically after the Sorting photon channels, Slicing data into bursts, as in the screenshot, did you encounter anything like this? do you have any suggestion? 

H2MM runs on the file HP3_TE50_SPC630.hdf5 without any issues, but does not work with the file minus8ta_minus6ntd_rpo_rt_1.hdf5  and so on.

Thank you
Mathi

<img width="1043" alt="Screen Shot 2021-05-10 at 4 33 19 PM" src="https://user-images.githubusercontent.com/31673579/117727321-7d9f9100-b1ad-11eb-9f21-f4f41a0ccad8.png">
<img width="1089" alt="Screen Shot 2021-05-05 at 5 41 59 PM" src="https://user-images.githubusercontent.com/31673579/117727331-8001eb00-b1ad-11eb-8952-2962dc353b0d.png">

**Comment by harripd** [comment]
Can you tell me what type of system this is running on?
This is a bug that I solved on a linux system, which should be re related to either a divide by zero error, or something to do with parallelization.

**Comment by mathicm** [comment]
Thank you again. I never tried Manjaro.
I also tried on ubuntu 20.04 LTS server and I get exact same error on the same 4th iteration, yes I changed the file so ignore the log-likelihood seen on the screenshot, but the error I get is same, I also tried several other HDF5 files but it gets exact same error at the same spot, only few files run successfully. I am helpless as I am not a linux or python expert just a novice. 

if this is divide by 0 error, how do i fix? 

alternatively If you could provide environment yml file, including specific version of "gcc" or the c compiler you use would be great help? 

Thank you

**Comment by harripd** [comment]
My gcc is version 10.2.0
I'm uploading a .yml to the github repository, so check that when it comes up.
Let me know if this fixes anything, although I have my doubts.
If using the .yml doesn't work, then try this, replace the line:
`h_mod_temp = EM_H2MM_C(h_modi_2[0],ph_index_da_2,ph_time_da_2)`
(in my version of the notebook it is line 8) with
`h_mod_temp = EM_H2MM_C(h_modi_2[1],ph_index_da_2,ph_time_da_2)`
all you are doing there is telling it to compute the 2 state model instead of the 1 state model. (just for debugging, this change will mess up some later parts of the notebook) and tell me how many iterations it goes until it ends.
I'm suspicious it's not a divide by 0, as 1 state models basically always converge on the 3rd or 4th iteration, and I should have checks for the divide by 0, my latest suspicion is that it has to do with the hand-off between the C code and Cython (the core algorithm is written in C, and I used cython to make a wrapper so that the code could be accessed in Python-- C is much faster, a pure python version was around 100 times slower) 

If you get a lot more iterations with the 2 state model, this would confirm my suspicions... and I would have you recompile the Cython code--- the current setup.py file uses only the .c file (H2MM_C.c), because I didn't want everyone to have to download cython as well, the H2MM_C.c file is generated by cython from the .pyx (cython) file, and one way or another, when making the H2MM_C library, it goes through H2MM_C.c

I'll upload the Cython-using setup.py file soon.

**Comment by mathicm** [comment]
I tried to run as you suggested with "h_mod_temp = EM_H2MM_C(h_modi_2[1],ph_index_da_2,ph_time_da_2) ",
it runs till 42nd iterations and then died.
when you are done with uploading the cython or .yml, I will try again.

Thank you for the details and willingness to help.

**Comment by mathicm** [comment]
you are correct env did not help, I get the exact same error even after creating the H2MM_env from your .yml file and redoing the c compiler step.

I will wait for your Cython-using setup.py, thank you.

**Comment by harripd** [comment]
The cython-using setup file is now in the repository as setupcy.py make sure you have H2MM_C.**pyx** in the directory with all the other files, otherwise it won't work.
Also, may I know more about the hdf5 files you are using? Are they nsALEX, and do they have anything additional, like anisotropy etc? I ask because depending, these _might_ change how the information is processed with FRETbursts, which could then impact how the data is fed into H2MM_C, which in turn could be a source of the error. All files I tested on were nsALEX, aka PIE, with no anisotropy etc., if you have differences, you may need to edit the `data_sort` function defined in the jupyter notebook, as it is built assuming that format, H2MM_C is able to handle other acquisition parameters, but the data must be pre-processed accordingly. Still, I tried to put in all the checks I could think of to always make H2MM_C give an error instead of crashing if something was wrong with the input data, so if this is the case, I'd really like to know, as it would mean that there is some scenario I did not think of that needs addressing in regards to data handling.

**Comment by mathicm** [comment]
I tried cython/setupcy.py to recompile but ends up exact same issue for my files, your files are working fine with your H2MM env build. 

The strange thing is, I have two files collected at same day with same settings without any changes, one works fine other file fails, all the files that fail happens at the exact same 4th iteration. FRETbursts alone has no issue with these data sets as I could do BVA, FRET histogram and so on.

I collect data using picoquant MT200 as .ptu files with 20MHz PIE excitation (32ps resolution) and with 2 channels and converted to hdf5 files using phconvert 0.9 and 0.5rc1 format, though I have 4 channel data collection with anisotropy, I only use 2 channel data for H2MM.

Would you mind to test/run my hdf5 files? I will be happy to share with you one of the file that fails.

Thank you

**Comment by harripd** [comment]
Hi mathicm,
I would be happy to test your files, I'll have a look. Just tell me where you put them.

**Comment by harripd** [comment]
Thanks for the files, it looks like the problem is the number of bursts. The main H2MM algorithm wasn't what was failing, but rather the Viterbi. Jupyter Notebooks however just didn't have a chance to display the final output of` EM_H2MM_C` before moving on to the `viterbi_sort` function, which is where the kernel actually crashed.
The crash itself was due to the function spinning up too many pthreads. Basically the `EM_H2MM_C` function only spins up the number of threads python tells it the system has- it assumes the system is multithreaded and so takes half of `os.cpu_count`(or you can manually set it with the optional argument `num_cores=x`), and each of those threads cooperate, taking successive bursts in turn,  but the `viterbi_sort` function spins up a separate pthread for each burst, and linux/pthreads couldn't handle all those threads.

I'm working on an updated version of `viterbi_sort` that will work the same way that `EM_H2MM_C` does, and so it won't crash when there are too many bursts. It may take a few days though. The other solution is to remove the multi-threading all together, it will make it a little bit slower, but considering that 99% of the time is taken in `EM_H2MM_C`, the extra time really isn't a huge concern.

**Comment by harripd** [comment]
The new files are up. I've tested them on my Manjaro machine and they all work, including when using your larger files.

Let me know if they fix the issue on your end.

**Comment by mathicm** [comment]
Thank you so much for your quick responses with code and willingness to test my data files. Yes, the new code works fine. I agree I do have lots of bursts which I will be reducing in the future data collections. I have also responded to your email, will follow up further.
